# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2018-11-05 06:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('guest_book', '0004_users'),
    ]

    operations = [
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=200, unique=True)),
                ('expires', models.DateTimeField()),
                ('user_s', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='guest_book.User')),
            ],
        ),
    ]
