# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-11-29 11:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('guest_book', '0005_session'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Users',
            new_name='ContactForm',
        ),
        migrations.RenameField(
            model_name='contactform',
            old_name='password',
            new_name='message',
        ),
        migrations.RenameField(
            model_name='contactform',
            old_name='username',
            new_name='subject',
        ),
    ]
